---
name: Ruff
on: 
   workflow_run:
       workflows: ["checks"]
       types: [completed]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Ruff scan and format
        uses: chartboost/ruff-action@v1